language: node_js

node_js:
  - "node"
  - "lts/*"

stages:
  - lint
  - compile
  - test
  - name: deploy
    if: branch = master

install:
  - npm ci
  - npm run config:peers

jobs:
  include:
    - stage: lint
      name: tslint
      script: npm run lint
    - stage: compile
      name: tsc
      script: 
        - npm run compile
        - npm run compile:browser
      
script:
  - npm run compile
  - npm run test -- --coverage --coverageReporters=text-lcov && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js